name: Expedition Reis
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23748
title: 'Travel adventures of Chris & April'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17171f'
    - '#9098a3'
    - '#4f5965'
    - '#e2e2e2'
    - '#028ed9'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.7029702486470342
  rhythmicContrast: 0.25
purpose: []
