name: Expedition Reis
favicon: null
layout_spectrum: 0.89195
typography_spectrum: 0.05085451668128371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.07089224481023848
  lightness: 0.15097657847218215
  saturation: 0.7029702486470342
  rhythmicContrast: 0.1781553472392261
purpose: []
